// Generated by TKG at 2021-06-06 10:58:59

#include "keymap_common.h"

#define KEYMAP_TKG( \
                        K0E, K0F, K0G, K0H, K0I, K0J, K0K, K0L, K0M, K0N, K0O, K0P, \
    K1A, K1B, K1C, K1D, K1E, K1F, K1G, K1H, K1I, K1J, K1K, K1L, K1M, K1N, K1O, K1P, \
    K2A, K2B, K2C, K2D, K2E, K2F, K2G, K2H, K2I, K2J, K2K, K2L, K2M, K2N, K2O, K2P, \
    K3A, K3B,      K3D, K3E, K3F, K3G, K3H, K3I, K3J,                               \
                                                                K4M,           K4P, \
    K5A, K5B, K5C,                                                                  \
    K1,                                                                               \
    K2,                                                                               \
    K3,                                                                               \
    K4,                                                                               \
    K5,                                                                               \
    K6,                                                                               \
    K7,                                                                               \
    K8,                                                                               \
    K14A,K14B,K14C,K14D,     K14F,K14G  \
) { \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_##K0E, KC_##K0F, KC_##K0G, KC_##K0H, KC_##K0I, KC_##K0J, KC_##K0K, KC_##K0L, KC_##K0M, KC_##K0N, KC_##K0O, KC_##K0P }, \
    { KC_##K1A, KC_##K1B, KC_##K1C, KC_##K1D, KC_##K1E, KC_##K1F, KC_##K1G, KC_##K1H, KC_##K1I, KC_##K1J, KC_##K1K, KC_##K1L, KC_##K1M, KC_##K1N, KC_##K1O, KC_##K1P }, \
    { KC_##K2A, KC_##K2B, KC_##K2C, KC_##K2D, KC_##K2E, KC_##K2F, KC_##K2G, KC_##K2H, KC_##K2I, KC_##K2J, KC_##K2K, KC_##K2L, KC_##K2M, KC_##K2N, KC_##K2O, KC_##K2P }, \
    { KC_##K3A, KC_##K3B, KC_NO,    KC_##K3D, KC_##K3E, KC_##K3F, KC_##K3G, KC_##K3H, KC_##K3I, KC_##K3J, KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_##K4M, KC_NO,    KC_NO,    KC_##K4P }, \
    { KC_##K5A, KC_##K5B, KC_##K5C, KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_##K14A,KC_##K14B,KC_##K14C,KC_##K14D,KC_NO,    KC_##K14F,KC_##K14G,KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }  \
}

#ifdef KEYMAP_SECTION_ENABLE
const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] __attribute__ ((section (".keymap.keymaps"))) = {
#else
const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] PROGMEM = {
#endif
    [0] = KEYMAP_TKG(
                            A,   B,   C,   D,   E,   F,   G,   H,   I,   J,   K,   L,    \
        M,   N,   O,   P,   Q,   R,   S,   T,   U,   V,   W,   X,   Y,   Z,   1,   2,    \
        3,   4,   5,   6,   7,   8,   9,   0,   ENT, ESC, BSPC,TAB, SPC, MINS,EQL, LBRC, \
        RBRC,BSLS,     SCLN,QUOT,GRV, COMM,DOT, SLSH,CAPS,                               \
                                                                    DEL,           RGHT, \
        LEFT,DOWN,UP,                                                                    \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        LCTL,LSFT,LALT,LGUI,     FN0, FN1),
    [1] = KEYMAP_TKG(
                            A,   B,   CALC,D,   E,   F,   G,   H,   I,   J,   K,   L,    \
        M,   N,   O,   PSCR,Q,   R,   S,   T,   U,   INS, W,   X,   Y,   Z,   F1,  F2,   \
        F3,  F4,  F5,  F6,  F7,  F8,  F9,  F10, ENT, ESC, DEL, TAB, SPC, F11, F12, LBRC, \
        RBRC,BSLS,     SCLN,QUOT,GRV, COMM,DOT, SLSH,CAPS,                               \
                                                                    DEL,           END,  \
        HOME,PGDN,PGUP,                                                                  \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        KC_NO,                                                                                \
        LCTL,LSFT,LALT,LGUI,     TRNS,TRNS),
};

#ifdef KEYMAP_SECTION_ENABLE
const action_t fn_actions[] __attribute__ ((section (".keymap.fn_actions"))) = {
#else
const action_t fn_actions[] PROGMEM = {
#endif
    [0] = ACTION_LAYER_MOMENTARY(1),
    [1] = ACTION_LAYER_TAP_KEY(1, KC_SPACE),
};