// Generated by TKG at 2017-12-22 17:26:53

#include "keymap_common.h"

#define KEYMAP_TKG( \
                        K0E, K0F, K0G, K0H, K0I, K0J, K0K, K0L, K0M, K0N, K0O, K0P, \
    K1A, K1B, K1C, K1D, K1E, K1F, K1G, K1H, K1I, K1J, K1K, K1L, K1M, K1N,           \
                                            K2I, K2J, K2K, K2L, K2M,           K2P, \
    K3A,           K3D, K3E,      K3G, K3H,                                         \
                                                      K4K,      K4M, K4N,      K4P, \
    K5A, K5B, K5C,                                                                  \
    K14A,K14B,K14C,K14D  \
) { \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_##K0E, KC_##K0F, KC_##K0G, KC_##K0H, KC_##K0I, KC_##K0J, KC_##K0K, KC_##K0L, KC_##K0M, KC_##K0N, KC_##K0O, KC_##K0P }, \
    { KC_##K1A, KC_##K1B, KC_##K1C, KC_##K1D, KC_##K1E, KC_##K1F, KC_##K1G, KC_##K1H, KC_##K1I, KC_##K1J, KC_##K1K, KC_##K1L, KC_##K1M, KC_##K1N, KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_##K2I, KC_##K2J, KC_##K2K, KC_##K2L, KC_##K2M, KC_NO,    KC_NO,    KC_##K2P }, \
    { KC_##K3A, KC_NO,    KC_NO,    KC_##K3D, KC_##K3E, KC_NO,    KC_##K3G, KC_##K3H, KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_##K4K, KC_NO,    KC_##K4M, KC_##K4N, KC_NO,    KC_##K4P }, \
    { KC_##K5A, KC_##K5B, KC_##K5C, KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_##K14A,KC_##K14B,KC_##K14C,KC_##K14D,KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }  \
}

#ifdef KEYMAP_SECTION_ENABLE
const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] __attribute__ ((section (".keymap.keymaps"))) = {
#else
const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] PROGMEM = {
#endif
    [0] = KEYMAP_TKG(
                            A,   B,   C,   D,   E,   F,   G,   H,   I,   J,   K,   L,    \
        M,   N,   O,   P,   Q,   R,   S,   T,   U,   V,   W,   X,   Y,   Z,              \
                                                FN1, ESC, BSPC,TAB, FN0,           LBRC, \
        RBRC,          SCLN,QUOT,     COMM,DOT,                                          \
                                                          HOME,     INS, END,      RGHT, \
        LEFT,DOWN,UP,                                                                  \
        LCTL,LSFT,LALT,LGUI),
    [1] = KEYMAP_TKG(
                            TRNS,TRNS,CALC,TRNS,3,   TRNS,TRNS,TRNS,8,   TRNS,TRNS,TRNS, \
        TRNS,TRNS,9,   0,   1,   4,   TRNS,5,   7,   TRNS,2,   TRNS,6,   TRNS,           \
                                                TRNS,TRNS,DEL, GRV, TRNS,          MINS, \
        EQL,           TRNS,TRNS,     SLSH,BSLS,                                         \
                                                          VOLU,     MUTE,VOLD,     END,  \
        HOME,PGDN,PGUP,                                                                  \
        CAPS,TRNS,TRNS,TRNS),
    [2] = KEYMAP_TKG(
                            TRNS,TRNS,TRNS,TRNS,F3,  TRNS,TRNS,TRNS,F10, TRNS,TRNS,TRNS, \
        TRNS,TRNS,F11, F12, F1,  F4,  TRNS,F5,  F9,  TRNS,F2,  TRNS,F8,  TRNS,           \
                                                TRNS,TRNS,TRNS,TRNS,TRNS,          TRNS, \
        TRNS,          TRNS,TRNS,     TRNS,TRNS,                                         \
                                                          TRNS,     TRNS,TRNS,     TRNS, \
        TRNS,TRNS,TRNS,                                                                  \
        TRNS,TRNS,TRNS,TRNS),
};

#ifdef KEYMAP_SECTION_ENABLE
const uint16_t fn_actions[] __attribute__ ((section (".keymap.fn_actions"))) = {
#else
const action_t fn_actions[] PROGMEM = {
#endif
    [0] = ACTION_LAYER_TAP_KEY(1, KC_SPACE),
    [1] = ACTION_LAYER_TAP_KEY(2, KC_ENTER),
};