// Generated by TKG at 2017-10-15 18:25:48

#include "keymap_common.h"

#define KEYMAP_TKG( \
                             K0F, K0G, K0H, K0I,                K0M,           K0P, \
         K1B,      K1D, K1E,           K1H,           K1K, K1L, K1M, K1N, K1O,      \
         K2B,      K2D,                     K2I, K2J, K2K, K2L, K2M,           K2P, \
         K3B,      K3D,      K3F,                K3J, K3K, K3L,      K3N, K3O, K3P, \
         K4B, K4C,      K4E, K4F,                          K4L,           K4O, K4P, \
    K5A, K5B, K5C, K5D,                K5H,                K5L,           K5O,      \
    K6A, K6B  \
) { \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_##K0F, KC_##K0G, KC_##K0H, KC_##K0I, KC_NO,    KC_NO,    KC_NO,    KC_##K0M, KC_NO,    KC_NO,    KC_##K0P }, \
    { KC_NO,    KC_##K1B, KC_NO,    KC_##K1D, KC_##K1E, KC_NO,    KC_NO,    KC_##K1H, KC_NO,    KC_NO,    KC_##K1K, KC_##K1L, KC_##K1M, KC_##K1N, KC_##K1O, KC_NO    }, \
    { KC_NO,    KC_##K2B, KC_NO,    KC_##K2D, KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_##K2I, KC_##K2J, KC_##K2K, KC_##K2L, KC_##K2M, KC_NO,    KC_NO,    KC_##K2P }, \
    { KC_NO,    KC_##K3B, KC_NO,    KC_##K3D, KC_NO,    KC_##K3F, KC_NO,    KC_NO,    KC_NO,    KC_##K3J, KC_##K3K, KC_##K3L, KC_NO,    KC_##K3N, KC_##K3O, KC_##K3P }, \
    { KC_NO,    KC_##K4B, KC_##K4C, KC_NO,    KC_##K4E, KC_##K4F, KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_##K4L, KC_NO,    KC_NO,    KC_##K4O, KC_##K4P }, \
    { KC_##K5A, KC_##K5B, KC_##K5C, KC_##K5D, KC_NO,    KC_NO,    KC_NO,    KC_##K5H, KC_NO,    KC_NO,    KC_NO,    KC_##K5L, KC_NO,    KC_NO,    KC_##K5O, KC_NO    }, \
    { KC_##K6A, KC_##K6B, KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }  \
}

#ifdef KEYMAP_SECTION_ENABLE
const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] __attribute__ ((section (".keymap.keymaps"))) = {
#else
const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] PROGMEM = {
#endif
    [0] = KEYMAP_TKG(
                                 A,   Q,   Y,   W,                  T,             F,    \
             Z,        G,   H,             K,             QUOT,COMM,B,   SPC, U,         \
             O,        FN0,                     R,   P,   LALT,BSLS,LCTL,          J,    \
             E,        V,        I,                  N,   BSPC,EQL,      SCLN,SLSH,LSFT, \
             L,   DOT,      ENT, M,                            PGUP,          PGDN,RGHT, \
        LEFT,DOWN,UP,  X,                  FN1,                S,             D,         \
        MINS,C),
    [1] = KEYMAP_TKG(
                                 TAB, 1,   6,   2,                  5,             TRNS, \
             ESC,      HOME,PGUP,          TRNS,          DOWN,TRNS,END, LBRC,7,         \
             9,        TRNS,                    4,   0,   TRNS,RGHT,GRV,           TRNS, \
             3,        TRNS,     8,                  PGDN,DEL, UP,       TRNS,BSLS,TRNS, \
             TRNS,SCLN,     RBRC,TRNS,                         TRNS,          TRNS,END,  \
        HOME,PGDN,PGUP,TRNS,               TRNS,               TRNS,          TRNS,      \
        TRNS,TRNS),
    [2] = KEYMAP_TKG(
                                 TAB, F1,  F6,  F2,                 F5,            TRNS, \
             TRNS,     TRNS,TRNS,          TRNS,          TRNS,TRNS,TRNS,TRNS,F7,        \
             F11,      TRNS,                    F4,  F12, TRNS,TRNS,TRNS,          TRNS, \
             F3,       TRNS,     F8,                 TRNS,TRNS,TRNS,     TRNS,TRNS,TRNS, \
             INS, TRNS,     TRNS,TRNS,                         TRNS,          TRNS,TRNS, \
        TRNS,TRNS,TRNS,TRNS,               TRNS,               TRNS,          TRNS,      \
        TRNS,TRNS),
};

#ifdef KEYMAP_SECTION_ENABLE
const uint16_t fn_actions[] __attribute__ ((section (".keymap.fn_actions"))) = {
#else
const action_t fn_actions[] PROGMEM = {
#endif
    [0] = ACTION_LAYER_MOMENTARY(1),
    [1] = ACTION_LAYER_MOMENTARY(2),
};
